import type { ToolCategory, ToolDef } from '@/types';
import { CONVERT_TOOLS } from './tools.convert';

export { CATEGORIES, STATUS_LABEL, type CategoryMeta } from './tools.meta';

/**
 * The full FileMint tool catalogue. This single list powers the Home quick
 * grid, the Convert / Edit / Tools hubs and global search. `status` is honest:
 * `ready` runs fully in the client, `beta` works with caveats, `backend` needs
 * the conversion server, `soon` has UI but no processing yet.
 */
export const PREMIUM_TOOL_IDS = new Set([
  'pdf-to-docx',
  'pptx-to-pdf',
  'pdf-to-xlsx',
  'pdf-to-html',
  'pdf-to-searchable',
  'add-signature',
  'add-stamp',
  'redact',
  'repair-pdf',
  'ocr',
]);

const TOOL_DEFS: ToolDef[] = [
  ...CONVERT_TOOLS,

  // ------------------------------------------------------------- Organize
  {
    id: 'merge',
    title: 'Merge PDF',
    subtitle: 'Combine into one file',
    icon: 'call-merge',
    accent: 'blue',
    category: 'organize',
    status: 'ready',
    route: '/merge',
    input: 'pdf',
    quick: true,
    keywords: ['combine', 'join'],
  },
  {
    id: 'split',
    title: 'Split PDF',
    subtitle: 'By range or every page',
    icon: 'call-split',
    accent: 'indigo',
    category: 'organize',
    status: 'ready',
    route: '/split',
    input: 'pdf',
    keywords: ['divide', 'separate', 'range'],
  },
  {
    id: 'compress',
    title: 'Compress PDF',
    subtitle: 'Reduce file size',
    icon: 'arrow-collapse-vertical',
    accent: 'emerald',
    category: 'organize',
    status: 'ready',
    route: '/compress',
    input: 'pdf',
    quick: true,
    keywords: ['shrink', 'optimize', 'reduce'],
  },
  {
    id: 'manage-pages',
    title: 'Manage Pages',
    subtitle: 'Reorder, rotate, delete',
    icon: 'file-document-multiple-outline',
    accent: 'teal',
    category: 'organize',
    status: 'ready',
    route: '/manage-pages',
    input: 'pdf',
    keywords: ['organize', 'pages', 'thumbnails'],
  },
  {
    id: 'reorder-pages',
    title: 'Reorder Pages',
    subtitle: 'Drag to rearrange',
    icon: 'sort',
    accent: 'sky',
    category: 'organize',
    status: 'ready',
    route: '/manage-pages?focus=reorder',
    input: 'pdf',
    keywords: ['arrange', 'move'],
  },
  {
    id: 'delete-pages',
    title: 'Delete Pages',
    subtitle: 'Remove unwanted pages',
    icon: 'file-remove-outline',
    accent: 'red',
    category: 'organize',
    status: 'ready',
    route: '/manage-pages?focus=delete',
    input: 'pdf',
    keywords: ['remove'],
  },
  {
    id: 'rotate-pages',
    title: 'Rotate Pages',
    subtitle: 'Fix orientation',
    icon: 'rotate-right',
    accent: 'amber',
    category: 'organize',
    status: 'ready',
    route: '/manage-pages?focus=rotate',
    input: 'pdf',
    keywords: ['turn', 'landscape'],
  },
  {
    id: 'extract-pages',
    title: 'Extract Pages',
    subtitle: 'Save pages as new PDF',
    icon: 'file-export-outline',
    accent: 'violet',
    category: 'organize',
    status: 'ready',
    route: '/manage-pages?focus=extract',
    input: 'pdf',
    keywords: ['pull', 'export'],
  },
  {
    id: 'duplicate-pages',
    title: 'Duplicate Pages',
    subtitle: 'Copy pages in place',
    icon: 'content-duplicate',
    accent: 'cyan',
    category: 'organize',
    status: 'ready',
    route: '/manage-pages?focus=duplicate',
    input: 'pdf',
    keywords: ['copy', 'clone'],
  },
  {
    id: 'add-blank-page',
    title: 'Add Blank Page',
    subtitle: 'Insert empty pages',
    icon: 'file-plus-outline',
    accent: 'slate',
    category: 'organize',
    status: 'ready',
    route: '/manage-pages?focus=insert',
    input: 'pdf',
    keywords: ['insert', 'empty'],
  },

  // ------------------------------------------------------------------ Edit
  {
    id: 'add-page-numbers',
    title: 'Page Numbers',
    subtitle: 'Number every page',
    icon: 'format-list-numbered',
    accent: 'indigo',
    category: 'edit',
    status: 'ready',
    route: '/pdf-editor?tool=add-page-numbers',
    input: 'pdf',
    keywords: ['number', 'pagination'],
  },
  {
    id: 'add-watermark',
    title: 'Add Watermark',
    subtitle: 'Stamp text on pages',
    icon: 'watermark',
    accent: 'sky',
    category: 'edit',
    status: 'ready',
    route: '/pdf-editor?tool=add-watermark',
    input: 'pdf',
    keywords: ['stamp', 'brand', 'confidential'],
  },
  {
    id: 'flatten',
    title: 'Flatten PDF',
    subtitle: 'Bake in form fields',
    icon: 'layers-outline',
    accent: 'slate',
    category: 'edit',
    status: 'ready',
    route: '/pdf-editor?tool=flatten',
    input: 'pdf',
    keywords: ['merge layers', 'forms'],
  },
  {
    id: 'crop-pdf',
    title: 'Crop PDF',
    subtitle: 'Trim page margins',
    icon: 'crop',
    accent: 'amber',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=crop-pdf',
    input: 'pdf',
    keywords: ['trim', 'margin'],
  },
  {
    id: 'add-text',
    title: 'Add Text',
    subtitle: 'Type onto the page',
    icon: 'format-text',
    accent: 'green',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=add-text',
    input: 'pdf',
    keywords: ['write', 'type'],
  },
  {
    id: 'add-signature',
    title: 'Add Signature',
    subtitle: 'Draw & place a signature',
    icon: 'draw',
    accent: 'rose',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=add-signature',
    input: 'pdf',
    keywords: ['sign', 'autograph'],
  },
  {
    id: 'doodle',
    title: 'Doodle / Draw',
    subtitle: 'Freehand on the page',
    icon: 'pencil-outline',
    accent: 'pink',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=doodle',
    input: 'pdf',
    keywords: ['draw', 'pen', 'sketch'],
  },
  {
    id: 'highlight',
    title: 'Highlight',
    subtitle: 'Mark up text',
    icon: 'marker',
    accent: 'yellow',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=highlight',
    input: 'pdf',
    keywords: ['marker', 'underline'],
  },
  {
    id: 'add-stamp',
    title: 'Add Stamp',
    subtitle: 'Approved, Draft, etc.',
    icon: 'stamper',
    accent: 'orange',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=add-stamp',
    input: 'pdf',
    keywords: ['approve', 'seal'],
  },
  {
    id: 'annotate',
    title: 'Annotate',
    subtitle: 'All markup tools',
    icon: 'comment-edit-outline',
    accent: 'violet',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=annotate',
    input: 'pdf',
    keywords: ['comment', 'note', 'markup'],
  },
  {
    id: 'redact',
    title: 'Redact',
    subtitle: 'Black out sensitive text',
    icon: 'marker-cancel',
    accent: 'slate',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=redact',
    input: 'pdf',
    keywords: ['hide', 'censor', 'private'],
  },
  {
    id: 'fill-forms',
    title: 'Fill Forms',
    subtitle: 'Add text, checks, dates, and signatures',
    icon: 'form-select',
    accent: 'blue',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=fill-forms',
    input: 'pdf',
    keywords: ['form', 'fields'],
  },

  // -------------------------------------------------------------- Security
  {
    id: 'lock-pdf',
    title: 'Lock PDF',
    subtitle: 'Protect with a password',
    icon: 'lock-outline',
    accent: 'red',
    category: 'security',
    status: 'backend',
    route: '/tool/lock-pdf',
    input: 'pdf',
    keywords: ['password', 'encrypt', 'protect'],
  },
  {
    id: 'unlock-pdf',
    title: 'Unlock PDF',
    subtitle: 'Remove a password',
    icon: 'lock-open-variant-outline',
    accent: 'green',
    category: 'security',
    status: 'backend',
    route: '/tool/unlock-pdf',
    input: 'pdf',
    keywords: ['password', 'decrypt'],
  },
  {
    id: 'pdf-permissions',
    title: 'Permissions',
    subtitle: 'Restrict print & copy',
    icon: 'shield-key-outline',
    accent: 'amber',
    category: 'security',
    status: 'backend',
    route: '/tool/pdf-permissions',
    input: 'pdf',
    keywords: ['restrict', 'rights'],
  },
  {
    id: 'repair-pdf',
    title: 'Repair PDF',
    subtitle: 'Fix corrupted files',
    icon: 'wrench-outline',
    accent: 'orange',
    category: 'security',
    status: 'backend',
    route: '/tool/repair-pdf',
    input: 'pdf',
    keywords: ['fix', 'corrupt', 'recover'],
  },

  // ------------------------------------------------------------------ Scan
  {
    id: 'scan-document',
    title: 'Smart Scan',
    subtitle: 'Camera document scanner',
    icon: 'line-scan',
    accent: 'teal',
    category: 'scan',
    status: 'beta',
    route: '/scan',
    input: 'camera',
    quick: true,
    keywords: ['camera', 'scanner', 'capture'],
  },
  {
    id: 'scan-id',
    title: 'Scan ID Card',
    subtitle: 'Front & back on one page',
    icon: 'card-account-details-outline',
    accent: 'sky',
    category: 'scan',
    status: 'beta',
    route: '/scan?mode=id',
    input: 'camera',
    keywords: ['id', 'card', 'license'],
  },
  {
    id: 'scan-passport',
    title: 'Scan Passport',
    subtitle: 'Passport preset',
    icon: 'passport',
    accent: 'indigo',
    category: 'scan',
    status: 'beta',
    route: '/scan?mode=passport',
    input: 'camera',
    keywords: ['passport', 'travel'],
  },
  {
    id: 'batch-scan',
    title: 'Batch Scan',
    subtitle: 'Many pages in a row',
    icon: 'camera-burst',
    accent: 'violet',
    category: 'scan',
    status: 'beta',
    route: '/scan?mode=batch',
    input: 'camera',
    keywords: ['multi', 'pages'],
  },

  // ------------------------------------------------------------------- OCR
  {
    id: 'ocr',
    title: 'OCR / Extract Text',
    subtitle: 'Save recognized text as TXT',
    icon: 'text-recognition',
    accent: 'purple',
    category: 'ocr',
    status: 'beta',
    route: '/ocr',
    input: 'any',
    quick: true,
    keywords: ['recognize', 'scan text', 'extract'],
  },

  // ------------------------------------------------------------------ View
  {
    id: 'import-pdf',
    title: 'Import PDF',
    subtitle: 'Open from your device',
    icon: 'file-import-outline',
    accent: 'blue',
    category: 'view',
    status: 'ready',
    route: '/tool/import-pdf',
    input: 'pdf',
    quick: true,
    keywords: ['open', 'upload', 'load'],
  },
  {
    id: 'open-pdf',
    title: 'Read PDF',
    subtitle: 'View with night mode',
    icon: 'book-open-page-variant-outline',
    accent: 'cyan',
    category: 'view',
    status: 'ready',
    route: '/tool/open-pdf',
    input: 'pdf',
    keywords: ['view', 'reader', 'preview'],
  },
  {
    id: 'open-document',
    title: 'Read Documents',
    subtitle: 'DOCX, PPTX, Excel, CSV, HTML',
    icon: 'file-eye-outline',
    accent: 'sky',
    category: 'view',
    status: 'ready',
    route: '/tool/open-document',
    input: 'any',
    quick: true,
    keywords: ['view', 'reader', 'preview', 'docx', 'pptx', 'xlsx', 'csv', 'html', 'text'],
  },
];

export const TOOLS: ToolDef[] = TOOL_DEFS.map((tool) =>
  PREMIUM_TOOL_IDS.has(tool.id)
    ? {
        ...tool,
        premium: true,
        premiumReason:
          'Premium unlocks higher quality processing, advanced editing, and priority server workflows for this tool.',
      }
    : tool,
);

export const QUICK_TOOLS = TOOLS.filter((t) => t.quick);

export function toolsByCategory(category: ToolCategory): ToolDef[] {
  return TOOLS.filter((t) => t.category === category);
}

export function findTool(id?: string | null): ToolDef | undefined {
  if (!id) return undefined;
  return TOOLS.find((t) => t.id === id);
}

/** Resolve an ordered list of tool ids, dropping any that don't exist. */
export function pickTools(ids: string[]): ToolDef[] {
  return ids.map((id) => TOOLS.find((t) => t.id === id)).filter((t): t is ToolDef => Boolean(t));
}

export function searchTools(query: string): ToolDef[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return TOOLS.filter((t) => {
    const haystack = [t.title, t.subtitle ?? '', ...(t.keywords ?? [])].join(' ').toLowerCase();
    return haystack.includes(q);
  });
}
