import type { AccentName } from '@/constants/theme';
import type { ToolCategory, ToolDef } from '@/types';

/**
 * The full FileMint tool catalogue. This single list powers the Home quick
 * grid, the Convert / Edit / Tools hubs and global search. `status` is honest:
 * `ready` runs fully in the client, `beta` works with caveats, `backend` needs
 * the conversion server, `soon` has UI but no processing yet.
 */
export const TOOLS: ToolDef[] = [
  // ---------------------------------------------------------------- Convert
  {
    id: 'image-to-pdf',
    title: 'Image to PDF',
    subtitle: 'JPG, PNG, WebP → PDF',
    icon: 'image-multiple',
    accent: 'violet',
    category: 'convert',
    status: 'ready',
    route: '/convert-to-pdf?profile=image',
    input: 'images',
    quick: true,
    keywords: ['photo', 'picture', 'jpg', 'png', 'webp', 'combine'],
  },
  {
    id: 'pdf-to-jpg',
    title: 'PDF to JPG',
    subtitle: 'Export pages as images',
    icon: 'file-jpg-box',
    accent: 'pink',
    category: 'convert',
    status: 'beta',
    route: '/tool/pdf-to-jpg',
    input: 'pdf',
    quick: true,
    keywords: ['image', 'export', 'jpeg'],
  },
  {
    id: 'pdf-to-png',
    title: 'PDF to PNG',
    subtitle: 'Export pages as PNG',
    icon: 'file-png-box',
    accent: 'fuchsia',
    category: 'convert',
    status: 'beta',
    route: '/tool/pdf-to-png',
    input: 'pdf',
    keywords: ['image', 'export'],
  },
  {
    id: 'docx-to-pdf',
    title: 'Word to PDF',
    subtitle: 'DOC, DOCX → PDF',
    icon: 'file-word-box',
    accent: 'blue',
    category: 'convert',
    status: 'backend',
    route: '/convert-to-pdf?profile=word',
    input: 'office',
    quick: true,
    keywords: ['doc', 'docx', 'word', 'office'],
  },
  {
    id: 'pdf-to-docx',
    title: 'PDF to Word',
    subtitle: 'Editable DOCX with tables',
    icon: 'file-word',
    accent: 'sky',
    category: 'convert',
    status: 'backend',
    route: '/tool/pdf-to-docx',
    input: 'pdf',
    keywords: ['doc', 'docx', 'word', 'editable'],
  },
  {
    id: 'pptx-to-pdf',
    title: 'PowerPoint to PDF',
    subtitle: 'PPT, PPTX → PDF',
    icon: 'file-powerpoint-box',
    accent: 'orange',
    category: 'convert',
    status: 'backend',
    route: '/convert-to-pdf?profile=ppt',
    input: 'office',
    keywords: ['ppt', 'pptx', 'slides', 'presentation'],
  },
  {
    id: 'pdf-to-pptx',
    title: 'PDF to PowerPoint',
    subtitle: 'Editable slides',
    icon: 'file-powerpoint',
    accent: 'amber',
    category: 'convert',
    status: 'backend',
    route: '/tool/pdf-to-pptx',
    input: 'pdf',
    keywords: ['ppt', 'pptx', 'slides'],
  },
  {
    id: 'xlsx-to-pdf',
    title: 'Excel to PDF',
    subtitle: 'XLS, XLSX → PDF',
    icon: 'file-excel-box',
    accent: 'green',
    category: 'convert',
    status: 'backend',
    route: '/convert-to-pdf?profile=excel',
    input: 'office',
    keywords: ['xls', 'xlsx', 'spreadsheet', 'sheet'],
  },
  {
    id: 'pdf-to-xlsx',
    title: 'PDF to Excel',
    subtitle: 'Tables to spreadsheet',
    icon: 'file-excel',
    accent: 'emerald',
    category: 'convert',
    status: 'backend',
    route: '/tool/pdf-to-xlsx',
    input: 'pdf',
    keywords: ['xls', 'xlsx', 'table', 'spreadsheet'],
  },
  {
    id: 'pdf-to-text',
    title: 'PDF to Text',
    subtitle: 'Extract plain text',
    icon: 'text-box-outline',
    accent: 'slate',
    category: 'convert',
    status: 'beta',
    route: '/tool/pdf-to-text',
    input: 'pdf',
    keywords: ['txt', 'extract'],
  },
  {
    id: 'pdf-to-html',
    title: 'PDF to HTML',
    subtitle: 'Web-ready markup',
    icon: 'language-html5',
    accent: 'orange',
    category: 'convert',
    status: 'backend',
    route: '/tool/pdf-to-html',
    input: 'pdf',
    keywords: ['web', 'html'],
  },
  {
    id: 'txt-to-pdf',
    title: 'Text to PDF',
    subtitle: 'TXT / Markdown → PDF',
    icon: 'file-document-outline',
    accent: 'cyan',
    category: 'convert',
    status: 'ready',
    route: '/convert-to-pdf?profile=text',
    input: 'any',
    keywords: ['txt', 'note', 'markdown'],
  },
  {
    id: 'csv-to-pdf',
    title: 'CSV to PDF',
    subtitle: 'Tabular data → PDF',
    icon: 'file-delimited-outline',
    accent: 'teal',
    category: 'convert',
    status: 'ready',
    route: '/convert-to-pdf?profile=csv',
    input: 'any',
    keywords: ['csv', 'table'],
  },
  {
    id: 'pdf-to-searchable',
    title: 'Searchable PDF',
    subtitle: 'Add an OCR text layer',
    icon: 'file-search-outline',
    accent: 'indigo',
    category: 'ocr',
    status: 'backend',
    route: '/tool/pdf-to-searchable',
    input: 'pdf',
    keywords: ['ocr', 'search', 'index'],
  },
  {
    id: 'batch-convert',
    title: 'Batch Convert',
    subtitle: 'Many files at once',
    icon: 'layers-triple-outline',
    accent: 'purple',
    category: 'convert',
    status: 'backend',
    route: '/convert-to-pdf?profile=batch',
    input: 'any',
    keywords: ['bulk', 'multiple'],
  },

  // ------------------------------------------------------------- Organize
  {
    id: 'merge',
    title: 'Merge PDF',
    subtitle: 'Combine into one file',
    icon: 'call-merge',
    accent: 'blue',
    category: 'organize',
    status: 'ready',
    route: '/merge',
    input: 'pdf',
    quick: true,
    keywords: ['combine', 'join'],
  },
  {
    id: 'split',
    title: 'Split PDF',
    subtitle: 'By range or every page',
    icon: 'call-split',
    accent: 'indigo',
    category: 'organize',
    status: 'ready',
    route: '/split',
    input: 'pdf',
    keywords: ['divide', 'separate', 'range'],
  },
  {
    id: 'compress',
    title: 'Compress PDF',
    subtitle: 'Reduce file size',
    icon: 'arrow-collapse-vertical',
    accent: 'emerald',
    category: 'organize',
    status: 'ready',
    route: '/compress',
    input: 'pdf',
    quick: true,
    keywords: ['shrink', 'optimize', 'reduce'],
  },
  {
    id: 'manage-pages',
    title: 'Manage Pages',
    subtitle: 'Reorder, rotate, delete',
    icon: 'file-document-multiple-outline',
    accent: 'teal',
    category: 'organize',
    status: 'ready',
    route: '/manage-pages',
    input: 'pdf',
    keywords: ['organize', 'pages', 'thumbnails'],
  },
  {
    id: 'reorder-pages',
    title: 'Reorder Pages',
    subtitle: 'Drag to rearrange',
    icon: 'sort',
    accent: 'sky',
    category: 'organize',
    status: 'ready',
    route: '/manage-pages?focus=reorder',
    input: 'pdf',
    keywords: ['arrange', 'move'],
  },
  {
    id: 'delete-pages',
    title: 'Delete Pages',
    subtitle: 'Remove unwanted pages',
    icon: 'file-remove-outline',
    accent: 'red',
    category: 'organize',
    status: 'ready',
    route: '/manage-pages?focus=delete',
    input: 'pdf',
    keywords: ['remove'],
  },
  {
    id: 'rotate-pages',
    title: 'Rotate Pages',
    subtitle: 'Fix orientation',
    icon: 'rotate-right',
    accent: 'amber',
    category: 'organize',
    status: 'ready',
    route: '/manage-pages?focus=rotate',
    input: 'pdf',
    keywords: ['turn', 'landscape'],
  },
  {
    id: 'extract-pages',
    title: 'Extract Pages',
    subtitle: 'Save pages as new PDF',
    icon: 'file-export-outline',
    accent: 'violet',
    category: 'organize',
    status: 'ready',
    route: '/manage-pages?focus=extract',
    input: 'pdf',
    keywords: ['pull', 'export'],
  },
  {
    id: 'duplicate-pages',
    title: 'Duplicate Pages',
    subtitle: 'Copy pages in place',
    icon: 'content-duplicate',
    accent: 'cyan',
    category: 'organize',
    status: 'ready',
    route: '/manage-pages?focus=duplicate',
    input: 'pdf',
    keywords: ['copy', 'clone'],
  },
  {
    id: 'add-blank-page',
    title: 'Add Blank Page',
    subtitle: 'Insert empty pages',
    icon: 'file-plus-outline',
    accent: 'slate',
    category: 'organize',
    status: 'ready',
    route: '/manage-pages?focus=insert',
    input: 'pdf',
    keywords: ['insert', 'empty'],
  },

  // ------------------------------------------------------------------ Edit
  {
    id: 'add-page-numbers',
    title: 'Page Numbers',
    subtitle: 'Number every page',
    icon: 'format-list-numbered',
    accent: 'indigo',
    category: 'edit',
    status: 'ready',
    route: '/pdf-editor?tool=add-page-numbers',
    input: 'pdf',
    keywords: ['number', 'pagination'],
  },
  {
    id: 'add-watermark',
    title: 'Add Watermark',
    subtitle: 'Stamp text on pages',
    icon: 'watermark',
    accent: 'sky',
    category: 'edit',
    status: 'ready',
    route: '/pdf-editor?tool=add-watermark',
    input: 'pdf',
    keywords: ['stamp', 'brand', 'confidential'],
  },
  {
    id: 'flatten',
    title: 'Flatten PDF',
    subtitle: 'Bake in form fields',
    icon: 'layers-outline',
    accent: 'slate',
    category: 'edit',
    status: 'ready',
    route: '/pdf-editor?tool=flatten',
    input: 'pdf',
    keywords: ['merge layers', 'forms'],
  },
  {
    id: 'crop-pdf',
    title: 'Crop PDF',
    subtitle: 'Trim page margins',
    icon: 'crop',
    accent: 'amber',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=crop-pdf',
    input: 'pdf',
    keywords: ['trim', 'margin'],
  },
  {
    id: 'add-text',
    title: 'Add Text',
    subtitle: 'Type onto the page',
    icon: 'format-text',
    accent: 'green',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=add-text',
    input: 'pdf',
    keywords: ['write', 'type'],
  },
  {
    id: 'add-signature',
    title: 'Add Signature',
    subtitle: 'Draw & place a signature',
    icon: 'draw',
    accent: 'rose',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=add-signature',
    input: 'pdf',
    keywords: ['sign', 'autograph'],
  },
  {
    id: 'doodle',
    title: 'Doodle / Draw',
    subtitle: 'Freehand on the page',
    icon: 'pencil-outline',
    accent: 'pink',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=doodle',
    input: 'pdf',
    keywords: ['draw', 'pen', 'sketch'],
  },
  {
    id: 'highlight',
    title: 'Highlight',
    subtitle: 'Mark up text',
    icon: 'marker',
    accent: 'yellow',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=highlight',
    input: 'pdf',
    keywords: ['marker', 'underline'],
  },
  {
    id: 'add-stamp',
    title: 'Add Stamp',
    subtitle: 'Approved, Draft, etc.',
    icon: 'stamper',
    accent: 'orange',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=add-stamp',
    input: 'pdf',
    keywords: ['approve', 'seal'],
  },
  {
    id: 'annotate',
    title: 'Annotate',
    subtitle: 'All markup tools',
    icon: 'comment-edit-outline',
    accent: 'violet',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=annotate',
    input: 'pdf',
    keywords: ['comment', 'note', 'markup'],
  },
  {
    id: 'redact',
    title: 'Redact',
    subtitle: 'Black out sensitive text',
    icon: 'marker-cancel',
    accent: 'slate',
    category: 'edit',
    status: 'beta',
    route: '/pdf-editor?tool=redact',
    input: 'pdf',
    keywords: ['hide', 'censor', 'private'],
  },
  {
    id: 'fill-forms',
    title: 'Fill Forms',
    subtitle: 'Complete PDF forms',
    icon: 'form-select',
    accent: 'blue',
    category: 'edit',
    status: 'soon',
    route: '/pdf-editor?tool=fill-forms',
    input: 'pdf',
    keywords: ['form', 'fields'],
  },

  // -------------------------------------------------------------- Security
  {
    id: 'lock-pdf',
    title: 'Lock PDF',
    subtitle: 'Protect with a password',
    icon: 'lock-outline',
    accent: 'red',
    category: 'security',
    status: 'backend',
    route: '/tool/lock-pdf',
    input: 'pdf',
    keywords: ['password', 'encrypt', 'protect'],
  },
  {
    id: 'unlock-pdf',
    title: 'Unlock PDF',
    subtitle: 'Remove a password',
    icon: 'lock-open-variant-outline',
    accent: 'green',
    category: 'security',
    status: 'backend',
    route: '/tool/unlock-pdf',
    input: 'pdf',
    keywords: ['password', 'decrypt'],
  },
  {
    id: 'pdf-permissions',
    title: 'Permissions',
    subtitle: 'Restrict print & copy',
    icon: 'shield-key-outline',
    accent: 'amber',
    category: 'security',
    status: 'backend',
    route: '/tool/pdf-permissions',
    input: 'pdf',
    keywords: ['restrict', 'rights'],
  },
  {
    id: 'repair-pdf',
    title: 'Repair PDF',
    subtitle: 'Fix corrupted files',
    icon: 'wrench-outline',
    accent: 'orange',
    category: 'security',
    status: 'backend',
    route: '/tool/repair-pdf',
    input: 'pdf',
    keywords: ['fix', 'corrupt', 'recover'],
  },

  // ------------------------------------------------------------------ Scan
  {
    id: 'scan-document',
    title: 'Smart Scan',
    subtitle: 'Camera document scanner',
    icon: 'line-scan',
    accent: 'teal',
    category: 'scan',
    status: 'beta',
    route: '/scan',
    input: 'camera',
    quick: true,
    keywords: ['camera', 'scanner', 'capture'],
  },
  {
    id: 'scan-id',
    title: 'Scan ID Card',
    subtitle: 'Front & back on one page',
    icon: 'card-account-details-outline',
    accent: 'sky',
    category: 'scan',
    status: 'beta',
    route: '/scan?mode=id',
    input: 'camera',
    keywords: ['id', 'card', 'license'],
  },
  {
    id: 'scan-passport',
    title: 'Scan Passport',
    subtitle: 'Passport preset',
    icon: 'passport',
    accent: 'indigo',
    category: 'scan',
    status: 'beta',
    route: '/scan?mode=passport',
    input: 'camera',
    keywords: ['passport', 'travel'],
  },
  {
    id: 'batch-scan',
    title: 'Batch Scan',
    subtitle: 'Many pages in a row',
    icon: 'camera-burst',
    accent: 'violet',
    category: 'scan',
    status: 'beta',
    route: '/scan?mode=batch',
    input: 'camera',
    keywords: ['multi', 'pages'],
  },

  // ------------------------------------------------------------------- OCR
  {
    id: 'ocr',
    title: 'OCR / Extract Text',
    subtitle: 'Read text from images',
    icon: 'text-recognition',
    accent: 'purple',
    category: 'ocr',
    status: 'beta',
    route: '/ocr',
    input: 'any',
    quick: true,
    keywords: ['recognize', 'scan text', 'extract'],
  },

  // ------------------------------------------------------------------ View
  {
    id: 'import-pdf',
    title: 'Import PDF',
    subtitle: 'Open from your device',
    icon: 'file-import-outline',
    accent: 'blue',
    category: 'view',
    status: 'ready',
    route: '/tool/import-pdf',
    input: 'pdf',
    quick: true,
    keywords: ['open', 'upload', 'load'],
  },
  {
    id: 'open-pdf',
    title: 'Read PDF',
    subtitle: 'View with night mode',
    icon: 'book-open-page-variant-outline',
    accent: 'cyan',
    category: 'view',
    status: 'ready',
    route: '/tool/open-pdf',
    input: 'pdf',
    keywords: ['view', 'reader', 'preview'],
  },
];

export interface CategoryMeta {
  key: ToolCategory;
  label: string;
  icon: string;
  accent: AccentName;
}

export const CATEGORIES: CategoryMeta[] = [
  { key: 'convert', label: 'Convert', icon: 'swap-horizontal', accent: 'violet' },
  { key: 'organize', label: 'Organize', icon: 'file-document-multiple-outline', accent: 'teal' },
  { key: 'edit', label: 'Edit PDF', icon: 'pencil-outline', accent: 'green' },
  { key: 'scan', label: 'Scan', icon: 'line-scan', accent: 'sky' },
  { key: 'ocr', label: 'OCR', icon: 'text-recognition', accent: 'purple' },
  { key: 'security', label: 'Security', icon: 'shield-lock-outline', accent: 'red' },
  { key: 'view', label: 'View & Read', icon: 'book-open-variant', accent: 'cyan' },
];

export const QUICK_TOOLS = TOOLS.filter((t) => t.quick);

export function toolsByCategory(category: ToolCategory): ToolDef[] {
  return TOOLS.filter((t) => t.category === category);
}

export function findTool(id?: string | null): ToolDef | undefined {
  if (!id) return undefined;
  return TOOLS.find((t) => t.id === id);
}

/** Resolve an ordered list of tool ids, dropping any that don't exist. */
export function pickTools(ids: string[]): ToolDef[] {
  return ids.map((id) => TOOLS.find((t) => t.id === id)).filter((t): t is ToolDef => Boolean(t));
}

export function searchTools(query: string): ToolDef[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return TOOLS.filter((t) => {
    const haystack = [t.title, t.subtitle ?? '', ...(t.keywords ?? [])].join(' ').toLowerCase();
    return haystack.includes(q);
  });
}

export const STATUS_LABEL: Record<ToolDef['status'], string> = {
  ready: 'Ready',
  beta: 'Beta',
  backend: 'Server',
  soon: 'Soon',
};
