import type { ToolDef } from '@/types';

export const CONVERT_TOOLS: ToolDef[] = [
  {
    id: 'image-to-pdf',
    title: 'Image to PDF',
    subtitle: 'JPG, PNG, WebP → PDF',
    icon: 'image-multiple',
    accent: 'violet',
    category: 'convert',
    status: 'ready',
    route: '/convert-to-pdf?profile=image',
    input: 'images',
    quick: true,
    keywords: ['photo', 'picture', 'jpg', 'png', 'webp', 'combine'],
  },
  {
    id: 'pdf-to-jpg',
    title: 'PDF to JPG',
    subtitle: 'Export pages as images',
    icon: 'file-jpg-box',
    accent: 'pink',
    category: 'convert',
    status: 'beta',
    route: '/tool/pdf-to-jpg',
    input: 'pdf',
    quick: true,
    keywords: ['image', 'export', 'jpeg'],
  },
  {
    id: 'pdf-to-png',
    title: 'PDF to PNG',
    subtitle: 'Export pages as PNG',
    icon: 'file-png-box',
    accent: 'fuchsia',
    category: 'convert',
    status: 'beta',
    route: '/tool/pdf-to-png',
    input: 'pdf',
    keywords: ['image', 'export'],
  },
  {
    id: 'docx-to-pdf',
    title: 'Word to PDF',
    subtitle: 'DOC, DOCX → PDF',
    icon: 'file-word-box',
    accent: 'blue',
    category: 'convert',
    status: 'backend',
    route: '/convert-to-pdf?profile=word',
    input: 'office',
    quick: true,
    keywords: ['doc', 'docx', 'word', 'office'],
  },
  {
    id: 'pdf-to-docx',
    title: 'PDF to Word',
    subtitle: 'Editable DOCX with tables',
    icon: 'file-word',
    accent: 'sky',
    category: 'convert',
    status: 'backend',
    route: '/tool/pdf-to-docx',
    input: 'pdf',
    keywords: ['doc', 'docx', 'word', 'editable'],
  },
  {
    id: 'pptx-to-pdf',
    title: 'PowerPoint to PDF',
    subtitle: 'PPT, PPTX → PDF',
    icon: 'file-powerpoint-box',
    accent: 'orange',
    category: 'convert',
    status: 'backend',
    route: '/convert-to-pdf?profile=ppt',
    input: 'office',
    keywords: ['ppt', 'pptx', 'slides', 'presentation'],
  },
  {
    id: 'pdf-to-pptx',
    title: 'PDF to PowerPoint',
    subtitle: 'Editable slides',
    icon: 'file-powerpoint',
    accent: 'amber',
    category: 'convert',
    status: 'backend',
    route: '/tool/pdf-to-pptx',
    input: 'pdf',
    keywords: ['ppt', 'pptx', 'slides'],
  },
  {
    id: 'xlsx-to-pdf',
    title: 'Excel to PDF',
    subtitle: 'XLS, XLSX → PDF',
    icon: 'file-excel-box',
    accent: 'green',
    category: 'convert',
    status: 'backend',
    route: '/convert-to-pdf?profile=excel',
    input: 'office',
    keywords: ['xls', 'xlsx', 'spreadsheet', 'sheet'],
  },
  {
    id: 'pdf-to-xlsx',
    title: 'PDF to Excel',
    subtitle: 'Tables to spreadsheet',
    icon: 'file-excel',
    accent: 'emerald',
    category: 'convert',
    status: 'backend',
    route: '/tool/pdf-to-xlsx',
    input: 'pdf',
    keywords: ['xls', 'xlsx', 'table', 'spreadsheet'],
  },
  {
    id: 'pdf-to-text',
    title: 'PDF to Text',
    subtitle: 'Extract plain text',
    icon: 'text-box-outline',
    accent: 'slate',
    category: 'convert',
    status: 'beta',
    route: '/tool/pdf-to-text',
    input: 'pdf',
    keywords: ['txt', 'extract'],
  },
  {
    id: 'pdf-to-html',
    title: 'PDF to HTML',
    subtitle: 'Web-ready markup',
    icon: 'language-html5',
    accent: 'orange',
    category: 'convert',
    status: 'backend',
    route: '/tool/pdf-to-html',
    input: 'pdf',
    keywords: ['web', 'html'],
  },
  {
    id: 'txt-to-pdf',
    title: 'Text to PDF',
    subtitle: 'TXT / Markdown → PDF',
    icon: 'file-document-outline',
    accent: 'cyan',
    category: 'convert',
    status: 'ready',
    route: '/convert-to-pdf?profile=text',
    input: 'any',
    keywords: ['txt', 'note', 'markdown'],
  },
  {
    id: 'csv-to-pdf',
    title: 'CSV to PDF',
    subtitle: 'Tabular data → PDF',
    icon: 'file-delimited-outline',
    accent: 'teal',
    category: 'convert',
    status: 'ready',
    route: '/convert-to-pdf?profile=csv',
    input: 'any',
    keywords: ['csv', 'table'],
  },
  {
    id: 'pdf-to-searchable',
    title: 'Searchable PDF',
    subtitle: 'Same look, selectable text',
    icon: 'file-search-outline',
    accent: 'indigo',
    category: 'ocr',
    status: 'backend',
    route: '/tool/pdf-to-searchable',
    input: 'pdf',
    keywords: ['ocr', 'search', 'index'],
  },
  {
    id: 'batch-convert',
    title: 'Batch Convert',
    subtitle: 'Many files at once',
    icon: 'layers-triple-outline',
    accent: 'purple',
    category: 'convert',
    status: 'backend',
    route: '/convert-to-pdf?profile=batch',
    input: 'any',
    keywords: ['bulk', 'multiple'],
  },
];
