import { StyleSheet } from 'react-native';

import { Radius, Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  hero: { alignItems: 'center', gap: Spacing.md, paddingVertical: Spacing.xxl },
  heroIcon: {
    width: 68,
    height: 68,
    borderRadius: Radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formatRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: Spacing.xs },
  formatPill: {
    borderWidth: 1,
    borderRadius: Radius.pill,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
  },
  preparingCard: { gap: Spacing.md },
  studio: { gap: Spacing.md },
  studioDesktop: { flexDirection: 'row', alignItems: 'flex-start' },
  leftRail: { gap: Spacing.sm },
  leftRailDesktop: { width: 330 },
  rightRail: { gap: Spacing.md },
  rightRailDesktop: { width: 355 },
  previewPane: { flex: 1, minWidth: 0, gap: Spacing.sm },
  summaryCard: { gap: Spacing.sm },
  pageList: { gap: Spacing.sm },
  pageTile: {
    borderWidth: 1,
    borderRadius: Radius.md,
    padding: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  pageThumb: { width: 48, height: 64, borderRadius: Radius.xs, backgroundColor: '#FFFFFF' },
  kindDot: {
    width: 24,
    height: 24,
    borderRadius: Radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tileActions: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  previewCard: { minHeight: 460, overflow: 'hidden', backgroundColor: '#6F747B' },
  previewToolbar: {
    minHeight: 60,
    borderBottomWidth: 1,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  previewWrap: { minHeight: 460, padding: Spacing.md, alignItems: 'center', justifyContent: 'center' },
  previewWrapFullscreen: { minHeight: 0, flex: 1, padding: Spacing.lg },
  previewStage: {
    width: '100%',
    maxWidth: 720,
    maxHeight: 720,
    borderRadius: Radius.xs,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
  },
  previewStageFullscreen: { maxWidth: '100%', maxHeight: '100%' },
  previewImage: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    backgroundColor: '#FFFFFF',
  },
  pageArrow: {
    position: 'absolute',
    top: '50%',
    marginTop: -22,
    backgroundColor: 'rgba(6,10,15,0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
  },
  pageArrowLeft: { left: Spacing.md },
  pageArrowRight: { right: Spacing.md },
  excludedBadge: {
    position: 'absolute',
    top: Spacing.lg,
    right: Spacing.lg,
    backgroundColor: 'rgba(0,0,0,0.62)',
    borderRadius: Radius.pill,
    paddingHorizontal: Spacing.md,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  selectedMeta: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  filmstripWrap: {
    borderWidth: 1,
    borderRadius: Radius.md,
    paddingVertical: Spacing.sm,
    minHeight: 112,
  },
  filmstripContent: { gap: Spacing.sm, paddingHorizontal: Spacing.sm },
  filmstripItem: {
    width: 74,
    borderWidth: 1,
    borderRadius: Radius.sm,
    padding: 5,
    gap: 5,
  },
  filmstripThumb: { width: '100%', height: 72, borderRadius: Radius.xs, backgroundColor: '#FFFFFF' },
  filmstripLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 14,
  },
  filmstripDot: { width: 7, height: 7, borderRadius: 4 },
  panel: { gap: Spacing.md },
  cropGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  filterScroller: { maxHeight: 244 },
  filterGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, paddingRight: Spacing.xs },
  filterChip: {
    width: 114,
    minHeight: 58,
    borderWidth: 1,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.sm,
    justifyContent: 'center',
    gap: 5,
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  actionsRow: { flexDirection: 'row', gap: Spacing.sm },
  actionButton: { flex: 1 },
  lockedScreen: { flex: 1, justifyContent: 'center', maxWidth: 560, alignSelf: 'center', width: '100%' },
  lockedCard: { alignItems: 'center', gap: Spacing.md },
  lockedIcon: {
    width: 78,
    height: 78,
    borderRadius: Radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cropHandle: {
    position: 'absolute',
    width: 34,
    height: 34,
    marginLeft: -17,
    marginTop: -17,
    borderRadius: 17,
  },
  cropHint: {
    position: 'absolute',
    left: Spacing.sm,
    bottom: Spacing.sm,
    borderWidth: 1,
    borderRadius: Radius.pill,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  fullscreenShell: { flex: 1 },
  fullscreenHeader: {
    minHeight: 68,
    borderBottomWidth: 1,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  fullscreenBody: { flex: 1, flexDirection: 'row', minHeight: 0 },
  fullscreenPreviewPane: { flex: 3, flexBasis: '60%', minWidth: 0, padding: Spacing.md, gap: Spacing.sm },
  fullscreenPreviewCard: { flex: 1, minHeight: 0, borderRadius: Radius.md, overflow: 'hidden' },
  fullscreenDashboard: { flex: 2, flexBasis: '40%', minWidth: 360, maxWidth: 760, borderLeftWidth: 1 },
  fullscreenDashboardContent: { padding: Spacing.md, gap: Spacing.md },
});
