import type { ImageStyle, TextStyle, ViewStyle } from 'react-native';

import { Radius, Spacing } from '@/constants/theme';

export const objectStyles = {
  drawHint: {
    position: 'absolute',
    left: 16,
    bottom: 16,
    minHeight: 34,
    borderRadius: Radius.pill,
    borderWidth: 1,
    paddingHorizontal: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  editorObject: {
    position: 'absolute',
    borderWidth: 2,
    borderRadius: Radius.sm,
    minWidth: 28,
    minHeight: 22,
  },
  objectFill: {
    flex: 1,
    borderWidth: 1,
    borderRadius: Radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.xs,
    overflow: 'hidden',
  },
  objectToolbar: {
    position: 'absolute',
    top: -38,
    left: 0,
    minHeight: 30,
    borderWidth: 1,
    borderRadius: Radius.pill,
    paddingHorizontal: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  resizeHandle: {
    position: 'absolute',
    width: 22,
    height: 22,
    borderRadius: Radius.pill,
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  resizeHandle_nw: { left: -11, top: -11 },
  resizeHandle_ne: { right: -11, top: -11 },
  resizeHandle_sw: { left: -11, bottom: -11 },
  resizeHandle_se: { right: -11, bottom: -11 },
  redactionFill: { backgroundColor: '#050505', borderColor: '#050505' },
  annotationFill: { backgroundColor: 'rgba(255,245,132,0.9)' },
  annotationShapeFill: { backgroundColor: 'transparent', borderWidth: 3 },
  annotationCalloutFill: { overflow: 'visible' },
  calloutPointer: {
    position: 'absolute',
    left: -8,
    bottom: -8,
    width: 18,
    height: 18,
    transform: [{ rotate: '45deg' }],
    opacity: 0.9,
  },
  formFieldFill: { borderWidth: 1.5, alignItems: 'stretch', justifyContent: 'center', gap: 2 },
  formFieldTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 4 },
  formCheckboxFill: {
    borderWidth: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: Spacing.xs,
  },
  formCheckboxBox: {
    width: 28,
    height: 28,
    borderRadius: Radius.xs,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formSignatureFill: { borderWidth: 1.5, alignItems: 'center', justifyContent: 'center', gap: 4 },
  formSignatureLine: { width: '84%', height: 2, borderRadius: Radius.pill },
  stampFill: { position: 'relative', backgroundColor: 'rgba(255,255,255,0.08)', borderWidth: 3, gap: 1 },
  stampPillFill: { borderRadius: Radius.pill },
  stampSealFill: { borderRadius: Radius.pill, aspectRatio: 1.55 },
  stampInnerBorder: {
    position: 'absolute',
    left: 6,
    right: 6,
    top: 6,
    bottom: 6,
    borderWidth: 1.5,
    borderRadius: Radius.xs,
  },
  stampUploadFill: { backgroundColor: 'rgba(255,255,255,0.02)', borderWidth: 1.5, padding: Spacing.xs },
  stampUploadPad: {
    height: 150,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.035)',
  },
  stampImagePreview: { width: '100%', height: '100%' },
  signatureFill: { backgroundColor: 'rgba(255,255,255,0.02)' },
  signatureObjectImage: { width: '100%', height: '100%' },
  watermarkFill: { backgroundColor: 'transparent', borderColor: 'transparent' },
  textFill: { alignItems: 'flex-start', justifyContent: 'center' },
  textObject: {
    position: 'absolute',
    left: '19%',
    top: '30%',
    width: '44%',
    minHeight: 74,
    borderWidth: 2,
    borderRadius: Radius.sm,
    padding: Spacing.sm,
  },
  floatingToolbar: {
    position: 'absolute',
    top: -42,
    left: 0,
    height: 34,
    borderWidth: 1,
    borderRadius: Radius.pill,
    paddingHorizontal: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  redactBox: {
    position: 'absolute',
    left: '22%',
    top: '42%',
    width: '48%',
    height: 48,
    backgroundColor: '#050505',
    borderWidth: 2,
  },
  highlightBox: {
    position: 'absolute',
    left: '18%',
    top: '36%',
    width: '56%',
    height: 42,
    borderWidth: 1.5,
    borderRadius: Radius.xs,
  },
  signaturePreview: {
    position: 'absolute',
    left: '42%',
    top: '70%',
    width: '34%',
    height: 82,
    borderWidth: 1.5,
    borderRadius: Radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-8deg' }],
  },
  stampPreview: {
    position: 'absolute',
    left: '24%',
    top: '55%',
    width: '48%',
    height: 92,
    borderWidth: 4,
    borderRadius: Radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-12deg' }],
  },
  watermarkPreview: {
    position: 'absolute',
    left: '10%',
    right: '10%',
    top: '42%',
    minHeight: 90,
    alignItems: 'center',
    justifyContent: 'center',
  },
  annotationPreview: {
    position: 'absolute',
    right: '10%',
    top: '18%',
    width: '28%',
    minHeight: 86,
    borderWidth: 1.5,
    borderRadius: Radius.sm,
    padding: Spacing.sm,
  },
} satisfies Record<string, ViewStyle | TextStyle | ImageStyle>;
