import { StyleSheet } from 'react-native';

import { Radius, Spacing } from '@/constants/theme';
import { objectStyles } from '@/components/pdf-editor/objectStyles';

export const styles = StyleSheet.create({
  root: { flex: 1 },
  lockedRoot: { alignItems: 'center', justifyContent: 'center', padding: Spacing.lg },
  lockedCard: {
    width: '100%',
    maxWidth: 520,
    borderWidth: 1,
    borderRadius: Radius.xl,
    padding: Spacing.xl,
    gap: Spacing.md,
  },
  topbar: {
    minHeight: 64,
    borderBottomWidth: 1,
    paddingHorizontal: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  topbarMobile: { borderBottomWidth: 1, paddingHorizontal: Spacing.sm, paddingBottom: Spacing.sm },
  mobileTopMain: { minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
  mobileToolbarContent: { gap: Spacing.sm, paddingHorizontal: Spacing.xs, paddingRight: Spacing.lg },
  titleBlock: { flex: 1, minWidth: 0 },
  toolbarGroup: { flexDirection: 'row', gap: 6 },
  zoomGroup: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  zoomPill: {
    minWidth: 58,
    height: 36,
    borderRadius: Radius.pill,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.sm,
  },
  pickShell: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: Spacing.lg },
  pickPanel: {
    width: '100%',
    maxWidth: 620,
    borderWidth: 1,
    borderRadius: Radius.xl,
    padding: Spacing.xl,
    gap: Spacing.md,
  },
  bigIcon: {
    width: 68,
    height: 68,
    borderRadius: Radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  pickSubtitle: { maxWidth: 420, alignSelf: 'center' },
  editorBody: { flex: 1, minHeight: 0 },
  editorBodyDesktop: { flexDirection: 'row' },
  editorBodyMobile: { flexDirection: 'column' },
  sidebar: { width: 164, borderRightWidth: 1, padding: Spacing.md, gap: Spacing.md },
  sidebarScroll: { gap: Spacing.md, paddingBottom: Spacing.xl },
  sideThumb: { borderWidth: 1, borderRadius: Radius.md, padding: Spacing.sm, gap: Spacing.xs },
  sideThumbImage: { width: '100%', aspectRatio: 0.72, borderRadius: Radius.sm, backgroundColor: '#fff' },
  canvasColumn: { flex: 1, minWidth: 0 },
  canvasHeader: {
    minHeight: 62,
    borderBottomWidth: 1,
    paddingHorizontal: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  canvasTitle: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  toolPill: {
    width: 38,
    height: 38,
    borderRadius: Radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  canvasNav: { flexDirection: 'row', gap: Spacing.xs },
  stage: { flex: 1, minHeight: 0 },
  stageScroll: { flex: 1 },
  stageContent: { minWidth: '100%', flexGrow: 1 },
  stageInner: {
    minHeight: '100%',
    minWidth: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.xl,
  },
  pageSurface: { backgroundColor: '#fff', borderRadius: Radius.sm, overflow: 'hidden' },
  pageImage: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, width: '100%', height: '100%' },
  loadingState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.md,
    padding: Spacing.xl,
  },
  settingsPanel: { width: 360, borderLeftWidth: 1 },
  mobileSheet: {
    maxHeight: 430,
    borderTopWidth: 1,
    borderTopLeftRadius: Radius.xl,
    borderTopRightRadius: Radius.xl,
  },
  settingsContent: { padding: Spacing.lg, gap: Spacing.md, paddingBottom: Spacing.xxl },
  settingsContentWithResultDock: { paddingBottom: 188 },
  panelHeader: { flexDirection: 'row', gap: Spacing.sm, alignItems: 'center' },
  toolScrollFrame: {
    position: 'relative',
    borderWidth: 1,
    borderRadius: Radius.xl,
    overflow: 'hidden',
    paddingVertical: 4,
  },
  toolScroll: { maxHeight: 54 },
  toolRail: { gap: Spacing.sm, paddingRight: Spacing.lg },
  toolScrollCue: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolChip: {
    height: 38,
    borderRadius: Radius.pill,
    borderWidth: 1,
    paddingHorizontal: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  labeled: { gap: Spacing.xs },
  actionWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  actionButton: {
    minHeight: 54,
    minWidth: 150,
    flex: 1,
    borderRadius: Radius.md,
    borderWidth: 1,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  actionButtonLabel: { flexShrink: 1 },
  mobileStrip: { borderTopWidth: 1, paddingVertical: Spacing.sm },
  mobileStripContent: { gap: Spacing.sm, paddingHorizontal: Spacing.md },
  stripThumb: {
    width: 70,
    borderWidth: 1,
    borderRadius: Radius.md,
    padding: 5,
    gap: 3,
    alignItems: 'center',
  },
  stripThumbImage: { width: '100%', aspectRatio: 0.72, borderRadius: Radius.sm, backgroundColor: '#fff' },
  cornerHandle: { position: 'absolute', width: 32, height: 32, borderRadius: Radius.sm, borderWidth: 4 },
  edgeHandle: { position: 'absolute', width: 24, height: 24, borderRadius: Radius.pill },
  dragHint: {
    position: 'absolute',
    height: 30,
    borderRadius: Radius.pill,
    borderWidth: 1,
    paddingHorizontal: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  magnifier: {
    position: 'absolute',
    width: 96,
    height: 54,
    borderRadius: Radius.lg,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  ...objectStyles,
  toast: {
    position: 'absolute',
    right: Spacing.lg,
    bottom: Spacing.lg,
    minHeight: 46,
    borderRadius: Radius.pill,
    paddingHorizontal: Spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  swatchRow: { flexDirection: 'row', gap: Spacing.sm },
  swatchRowWrap: { flexWrap: 'wrap' },
  swatch: { width: 32, height: 32, borderRadius: Radius.pill, borderWidth: 3 },
  twoCols: { width: '100%', flexDirection: 'row', gap: Spacing.sm },
  twoColItem: { flex: 1, minWidth: 0 },
  positionGrid: {
    borderWidth: 1,
    borderRadius: Radius.md,
    overflow: 'hidden',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  positionCell: {
    width: '33.333%',
    aspectRatio: 2.1,
    borderWidth: 0.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  positionDot: { width: 10, height: 10, borderRadius: Radius.pill },
  checkRow: {
    minHeight: 46,
    borderWidth: 1,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  warningBox: {
    borderWidth: 1,
    borderRadius: Radius.md,
    padding: Spacing.md,
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  resultPanel: { borderWidth: 1, borderRadius: Radius.lg, padding: Spacing.md, gap: Spacing.md },
  resultHeader: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  resultIcon: {
    width: 28,
    height: 28,
    borderRadius: Radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultActions: { gap: Spacing.sm },
  mobileResultDock: {
    position: 'absolute',
    left: Spacing.md,
    right: Spacing.md,
    bottom: Spacing.md,
    borderWidth: 1,
    borderRadius: Radius.xl,
    padding: Spacing.md,
    gap: Spacing.sm,
  },
  mobileResultTitle: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  mobileResultButtons: { flexDirection: 'row', gap: Spacing.sm },
  mobileResultButton: { flex: 1 },
  signaturePad: {
    height: 132,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  signatureDrawPad: { position: 'relative' },
  signatureTypedPad: { paddingHorizontal: Spacing.md },
  signaturePadEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
  },
  signatureImagePreview: { width: '100%', height: '100%' },
  stampGallery: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  stampChip: {
    minHeight: 40,
    minWidth: 96,
    borderWidth: 2,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-4deg' }],
  },
  stampChipPill: { borderRadius: Radius.pill },
  stampChipSeal: { minWidth: 74, borderRadius: Radius.pill, transform: [{ rotate: '-8deg' }] },
  commentRow: {
    borderRadius: Radius.md,
    padding: Spacing.md,
    backgroundColor: 'rgba(255,255,255,0.045)',
    gap: 2,
  },
  formFieldList: { gap: Spacing.sm },
  formDetectedRow: {
    minHeight: 54,
    borderRadius: Radius.md,
    padding: Spacing.sm,
    backgroundColor: 'rgba(255,255,255,0.045)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  formDetectedIndex: {
    width: 28,
    height: 28,
    borderRadius: Radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickNoteGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  quickNoteChip: {
    minHeight: 34,
    maxWidth: '100%',
    borderRadius: Radius.pill,
    paddingHorizontal: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.045)',
  },
});
